### ISSUE TITLE
error with resubmitting of jobs

### ISSUE THREAD

**Issue by marmeyer** [dgonzal/SFrameBatch#33] opened 2016-01-07 09:54 UTC
Hi! I get the following error message when I try to resubmit my jobs:

Found Submission Info for WW
Found Submission Info for WZ
Found Submission Info for ZZ
Found Submission Info for Data
error: fread("/") failed: Is a directory
Unable to read script file because of error: error reading from file /
Traceback (most recent call last):
  File "/afs/desy.de/user/m/mameyer/xxl-af-cms/CMSSW_7_4_15_patch1/src/UHH2/SFrameBatch/sframe_batch.py", line 115, in <module>
    if options.resubmit: manager.resubmit_jobs()
  File "/afs/desy.de/user/m/mameyer/xxl-af-cms/CMSSW_7_4_15_patch1/src/UHH2/SFrameBatch/Manager.py", line 177, in resubmit_jobs
    process.pids[it-1] = resubmit(self.workdir+'/Stream_'+process.name,process.name+'_'+str(it),self.workdir,self.header)
  File "/afs/desy.de/user/m/mameyer/xxl-af-cms/CMSSW_7_4_15_patch1/src/UHH2/SFrameBatch/batch_classes.py", line 92, in resubmit
    return proc_qstat.communicate()[0].split()[2]
IndexError: list index out of range

I do not understand what is wrong. It would be great  if somebody could help me with this.

Best, 

Mareike

**Comment by dgonzal** [comment] 2016-01-07 11:18
Hi mareike,
the problem is that when resubmitting your jobs sframe batch expects to get the pid of your job from the batch to monitor your jobs. This fails when you get this error message. Since the bird cluster is having some trouble it just might need time, that they fix there problems. 

If the bird problems stay one can change some stuff.

Cheers 

Daniel

**Comment by marmeyer** [comment] 2016-01-07 16:42
Hi Daniel!

I still have the same problem and I already had it with some jobs before Christmas. So it would be really great if there would be a solution for this:) Is it difficult/time consuming to fix this?

Thanks for your help!

Mareike

**Comment by dgonzal** [comment] 2016-01-10 15:44
Hi Mareike,

would be nice if I could have a look at it, even if it is the same as last time. Maybe monday?

Cheers 

Daniel

**Comment by dgonzal** [comment] 2016-02-15 15:43
since I did not hear anything for some time I will close this thread

**Closed as completed by dgonzal** 2016-02-15 15:43 UTC
