### ISSUE TITLE
hadd without trees

### ISSUE THREAD

**Issue by HeinerTholen** [dgonzal/SFrameBatch#9] opened 2015-10-31 13:17 UTC
in the current implementation, files are omitted from hadd, if they have 0 events in their analysis tree. This is problematic, because there can be histograms in these files (filled before the event-selection) that need to be merged nevertheless. 

I know you wanted to squelch the ugly message by hadd, but the only way I see for that is to decrease verbosity with the -v option.

**Comment by dgonzal** [comment] 2015-10-31 16:26
forgot about the histograms. commented out the lines. now the warning is back. as far as I know the problem is the ordering of the files. if the first file has no tree hadd gets confused. Will work on this the next days.

**Comment by dgonzal** [comment] 2015-11-24 18:24
I will close this for now. Did change it to always starting with a file with trees (if such file exists). Remaining warnings simply have to be ignored. verbosity == 0 is not my preferred option since no errors (?) would be printed

**Closed as completed by dgonzal** 2015-11-24 18:24 UTC
